# Importing Libraries

In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from tensorflow import keras

# Data Preprocessing

### 1. Training Image preprocessing

In [3]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    verbose=True,
)

Found 70295 files belonging to 38 classes.


### 2. Validation Image Preprocessing

In [4]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="int",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
    pad_to_aspect_ratio=False,
    data_format=None,
    verbose=True,
)

Found 17572 files belonging to 38 classes.


In [7]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int32, name=None))>

In [9]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[194.25 190.25 191.25]
   [181.   177.   178.  ]
   [184.25 180.25 181.25]
   ...
   [150.75 142.75 140.75]
   [162.75 154.75 152.75]
   [147.   139.   137.  ]]

  [[184.   180.   181.  ]
   [174.   170.   171.  ]
   [208.25 204.25 205.25]
   ...
   [146.25 138.25 136.25]
   [155.   147.   145.  ]
   [158.25 150.25 148.25]]

  [[202.5  198.5  199.5 ]
   [187.5  183.5  184.5 ]
   [179.5  175.5  176.5 ]
   ...
   [152.   144.   142.  ]
   [160.   152.   150.  ]
   [153.   145.   143.  ]]

  ...

  [[193.75 191.75 192.75]
   [192.   190.   191.  ]
   [185.   183.   184.  ]
   ...
   [160.75 152.75 150.75]
   [162.   154.   152.  ]
   [154.   146.   144.  ]]

  [[186.25 184.25 185.25]
   [186.75 184.75 185.75]
   [183.   181.   182.  ]
   ...
   [164.75 156.75 154.75]
   [161.5  153.5  151.5 ]
   [161.25 153.25 151.25]]

  [[187.25 185.25 186.25]
   [187.25 185.25 186.25]
   [182.75 180.75 181.75]
   ...
   [164.   156.   154.  ]
   [159.75 151.75 149.75]
   [165.75 157.75 15

# Building model

In [13]:
from tensorflow.keras.layers import Dense,Conv2D,MaxPool2D
from tensorflow.keras.models import Sequential

In [14]:
model=Sequential()

In [15]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

C:\Users\WINDOWS 10\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
